[build]
  publish = "."
  
# Simple static site - no functions needed
# Forms handled by Netlify's built-in form processing
  
# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  SITE_URL = "https://ekosolarpros.com"